# Generated by Django 5.0.7 on 2024-08-04 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, default='pythonlogo.png', upload_to='')),
            ],
        ),
    ]
