# Generated by Django 5.0.7 on 2024-08-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
