# Generated by Django 5.0.7 on 2024-08-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_users'),
    ]

    operations = [
    ]
