# Generated by Django 5.0.7 on 2024-08-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_author'),
    ]

    operations = [
    ]
