# Generated by Django 5.0.7 on 2024-08-04 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetest', '0002_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
