# Generated by Django 5.0.7 on 2024-08-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetest', '0003_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
